services:
  docs:
    image: taxi_basalt_website_local_docs
    container_name: taxi_basalt_website_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./taxi_basalt_website:/app/taxi_basalt_website:z
    ports:
      - '9000:9000'
    command: /start-docs
