# Generated by Django 5.0.12 on 2025-04-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_header', models.CharField(max_length=100, verbose_name='Telefon Kopf Text')),
                ('telephone_text', models.CharField(max_length=200, verbose_name='Telefon Text')),
                ('fax_header', models.CharField(max_length=100, verbose_name='Fax Kopf Text')),
                ('fax_text', models.CharField(max_length=200, verbose_name='Fax Text')),
                ('mobile_header', models.CharField(max_length=100, verbose_name='Mobil Kopf Text')),
                ('mobile_text', models.CharField(max_length=200, verbose_name='Mobil Text')),
                ('email_header', models.CharField(max_length=100, verbose_name='Email Kopf Text')),
                ('email_text', models.CharField(max_length=200, verbose_name='Email Text')),
                ('website_header', models.CharField(max_length=100, verbose_name='Website Kopf Text')),
                ('website_text', models.CharField(max_length=200, verbose_name='Website Text')),
                ('address_header', models.CharField(max_length=100, verbose_name='Adresse Kopf Text')),
                ('address_text', models.CharField(max_length=200, verbose_name='Adresse Text')),
                ('logo', models.ImageField(upload_to='footer/', verbose_name='Logo')),
            ],
        ),
    ]
