# Generated by Django 5.0.12 on 2025-04-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_basalt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='address_text',
            field=models.TextField(verbose_name='Adresse Text'),
        ),
    ]
