# Generated by Django 5.0.12 on 2025-04-04 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_basalt', '0002_alter_footersection_address_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_header', models.CharField(max_length=100, verbose_name='Kopf Text')),
                ('hero_text', models.CharField(max_length=200, verbose_name='Text')),
                ('hero_button_text', models.CharField(max_length=50, verbose_name='Button Text')),
                ('hero_image', models.ImageField(upload_to='hero_images/', verbose_name='Bild')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Kopf Text')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Kopf Text')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('detail_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detail Titel')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('home_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='taxi_basalt.servicesection')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Kopf Text')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='Bild')),
                ('vehicle_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='taxi_basalt.vehiclesection')),
            ],
        ),
    ]
