# Generated by Django 5.0.12 on 2025-04-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_basalt', '0003_homesection_servicesection_vehiclesection_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Kopf Text')),
                ('location_latitude', models.CharField(max_length=100, verbose_name='Standort Latitude')),
                ('location_longitude', models.CharField(max_length=100, verbose_name='Standort Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Imprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Kopf Text')),
                ('firm_name_part_one', models.CharField(max_length=100, verbose_name='Erster Teil des Firmenname')),
                ('firm_name_part_two', models.CharField(max_length=100, verbose_name='Zweiter Teil des Firmenname')),
                ('firm_address_part_one', models.CharField(max_length=100, verbose_name='Straße und Hausnummer der Adreese')),
                ('firm_address_part_two', models.CharField(max_length=100, verbose_name='Postleitzahl der Adresse')),
                ('phone_header', models.CharField(max_length=100, verbose_name='Telefon Kopf Text')),
                ('phone_text', models.CharField(max_length=100, verbose_name='Telefon Text')),
                ('fax_header', models.CharField(max_length=100, verbose_name='Fax Kopf Text')),
                ('fax_text', models.CharField(max_length=100, verbose_name='Fax Text')),
                ('mobile_header', models.CharField(max_length=100, verbose_name='Mobil Kopf Text')),
                ('mobile_text', models.CharField(max_length=100, verbose_name='Mobil Text')),
                ('email_header', models.CharField(max_length=100, verbose_name='Email Kopf Text')),
                ('email_text', models.CharField(max_length=100, verbose_name='Email Text')),
                ('website_header', models.CharField(max_length=100, verbose_name='Website Kopf Text')),
                ('website_text', models.CharField(max_length=100, verbose_name='Website Text')),
                ('ceo_header', models.CharField(max_length=100, verbose_name='Ceo Kopfzeile')),
                ('ceo_text', models.CharField(max_length=100, verbose_name='Ceo Name')),
                ('commercial_register_header', models.CharField(max_length=100, verbose_name='Handelsregister Kopf Text')),
                ('commercial_register_text', models.CharField(max_length=100, verbose_name='Handelsregister Text')),
            ],
        ),
    ]
