# Generated by Django 5.0.12 on 2025-04-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_basalt', '0004_findus_imprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.TextField(verbose_name='Dienstleistung Text'),
        ),
    ]
